/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V1.1.0
 * Contact: avishaybennatan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FileResource } from './fileResource';
import { FileUpdate } from './fileUpdate';
import { BasicContainer } from './basicContainer';



export interface FileUpdateContainer extends BasicContainer{
   

    updateCompleted?: boolean;

    updateStarted?: boolean;

    nextIssueDate?: Date;

    lastDateCompleted?: Date;

    lastDateStarted?: Date;

    lastDateVerified?: Date;

    interval?: number;

    periodicFileResources?: Array<FileResource>;

    software?: FileUpdate;

    keepOriginal?: boolean;

    locationOnDevice?: string;

    getFromDevice?: boolean;

    extensionAsSource?: string;

    shouldExtract?: boolean;

    deleteAfterExract?: boolean;

    newFormat?: boolean;

    generationRequest?: string;

}
