/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V1.1.0
 * Contact: avishaybennatan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParameterInfo } from './parameterInfo';


export interface InvokerMethodInfo { 
    name?: string; //name to provide when refering to this methd
    description?: string; // human readable description
    displayName?: string; // human readable name
    returnType?: string; //return type of invocation
    categories?:string[];
    relatedMethodNames?:string[];
    parameterHolderType?: string; // java canonical name (equals to json-type) of the object inheriting from ExecutionParametersHolder
    parameters?: Array<ParameterInfo>; //list of parameters info on $parameterHolderType type object
}
