/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V1.1.0
 * Contact: avishaybennatan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Baseclass } from './baseclass';
import { FileResource } from './fileResource';
import { Tenant } from './tenant';
import { UpdateableDevice } from './updateableDevice';


export interface LogRequest extends Baseclass{


    updateableDevice?: UpdateableDevice;

    logFile?: FileResource;

    level?: LogRequest.LevelEnum;

    filtering?: string;

    logGeatherStarted?: boolean;

    logGeatherCompleted?: boolean;

    logDate?: Date;

}
export namespace LogRequest {
    export enum LevelEnum {
        SEVERE = <any> 'SEVERE',
        WARNING = <any> 'WARNING',
        INFO = <any> 'INFO'
    }
}
