/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V1.1.0
 * Contact: avishaybennatan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Baseclass } from './baseclass';
import { Tenant } from './tenant';
import { TenantToBaseClassPremission } from './tenantToBaseClassPremission';
import { FileResource } from './fileResource';


export interface Tenant extends Baseclass{
  
    externalId?: string;

    tenantToBaseClassPremissions?: Array<TenantToBaseClassPremission>;

    apiKey?: string;
    icon?:FileResource;

}
