/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V1.1.0
 * Contact: avishaybennatan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { FlexiCoreDecycle } from './flexiCoreDecycle';
import { Observable } from 'rxjs/Observable';

import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';
import { HttpHeaders, HttpClient, HttpResponse, HttpEvent } from '@angular/common/http';
import { PasswordSecurityPolicy } from '../model/passwordSecurityPolicy';
import { PasswordSecurityPolicyCreate } from '../model/passwordSecurityPolicyCreate';
import { PasswordSecurityPolicyUpdate } from '../model/passwordSecurityPolicyUpdate';
import { PasswordSecurityPolicyFilter } from '../model/passwordSecurityPolicyFilter';
import { PaginationResponse } from '../model/models';


@Injectable()
export class PasswordSecurityPolicyService {

    protected basePath = 'https://192.168.0.41:8080/FlexiCore/rest';
    public defaultHeaders = new HttpHeaders();
    public configuration: Configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            let url = basePath.split("/");
            this.basePath = url[0] + "//" + url[2];
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     *  
     * @param authenticationkey The AuthenticationKey retrieved when sign-in into the system
     * @param body 
     */
    public createPolicy(authenticationkey?: string, body?: PasswordSecurityPolicyCreate, observe?: 'body', reportProgress?: boolean): Observable<PasswordSecurityPolicy>;
    public createPolicy(authenticationkey?: string, body?: PasswordSecurityPolicyCreate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PasswordSecurityPolicy>>;
    public createPolicy(authenticationkey?: string, body?: PasswordSecurityPolicyCreate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PasswordSecurityPolicy>>;
    public createPolicy(authenticationkey?: string, body?: PasswordSecurityPolicyCreate, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PasswordSecurityPolicy>(`${this.basePath}/passwordSecurityPolicy/create`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).map(o => FlexiCoreDecycle.retrocycle(o));
    }

    /**
     *  
     * @param authenticationkey The AuthenticationKey retrieved when sign-in into the system
     * @param body 
     */
    public updatePolicy(authenticationkey?: string, body?: PasswordSecurityPolicyUpdate, observe?: 'body', reportProgress?: boolean): Observable<PasswordSecurityPolicy>;
    public updatePolicy(authenticationkey?: string, body?: PasswordSecurityPolicyUpdate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PasswordSecurityPolicy>>;
    public updatePolicy(authenticationkey?: string, body?: PasswordSecurityPolicyUpdate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PasswordSecurityPolicy>>;
    public updatePolicy(authenticationkey?: string, body?: PasswordSecurityPolicyUpdate, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<PasswordSecurityPolicy>(`${this.basePath}/passwordSecurityPolicy/update`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).map(o => FlexiCoreDecycle.retrocycle(o));
    }

    /**
     *  
     * @param authenticationkey The AuthenticationKey retrieved when sign-in into the system
     * @param body 
     */
    public getAllPolicy(authenticationkey?: string, body?: PasswordSecurityPolicyFilter, observe?: 'body', reportProgress?: boolean): Observable<PaginationResponse<PasswordSecurityPolicy>>;
    public getAllPolicy(authenticationkey?: string, body?: PasswordSecurityPolicyFilter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PaginationResponse<PasswordSecurityPolicy>>>;
    public getAllPolicy(authenticationkey?: string, body?: PasswordSecurityPolicyFilter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PaginationResponse<PasswordSecurityPolicy>>>;
    public getAllPolicy(authenticationkey?: string, body?: PasswordSecurityPolicyFilter, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PaginationResponse<PasswordSecurityPolicy>>(`${this.basePath}/passwordSecurityPolicy/getAll`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).map(o => FlexiCoreDecycle.retrocycle(o));
    }
}
