/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V3.2.0
 * Contact: avishay@flexi-core.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpEvent } from '@angular/common/http';

import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { CreatePermissionGroupLinkRequest } from '../model/createPermissionGroupLinkRequest';
import { CreatePermissionGroupRequest } from '../model/createPermissionGroupRequest';
import { FilteringInformationHolder } from '../model/filteringInformationHolder';
import { PermissionGroup } from '../model/permissionGroup';
import { PermissionGroupToBaseclass } from '../model/permissionGroupToBaseclass';

import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';
import { UpdatePermissionGroup } from '../model/updatePermissionGroup';
import { FlexiCoreDecycle } from './api';
import { PermissionGroupCopy } from '../model/models';


@Injectable()
export class PermissionGroupService {

    protected basePath = '/FlexiCore';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * connectPermissionGroupToBaseclass
     * Connects Permission Group To Baseclass 
     * @param body 
     * @param authenticationkey 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public connectPermissionGroupToBaseclass(body?: CreatePermissionGroupLinkRequest, authenticationkey?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<PermissionGroupToBaseclass>>;
    public connectPermissionGroupToBaseclass(body?: CreatePermissionGroupLinkRequest, authenticationkey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PermissionGroupToBaseclass>>>;
    public connectPermissionGroupToBaseclass(body?: CreatePermissionGroupLinkRequest, authenticationkey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PermissionGroupToBaseclass>>>;
    public connectPermissionGroupToBaseclass(body?: CreatePermissionGroupLinkRequest, authenticationkey?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;
        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put(`${this.basePath}/permissionGroup/connectPermissionGroupToBaseclass`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o => FlexiCoreDecycle.retrocycle(o)));
    }

    /**
     * createPermissionGroup
     * creates Permission Group
     * @param body 
     * @param authenticationkey 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPermissionGroup(body?: CreatePermissionGroupRequest, authenticationkey?: string, observe?: 'body', reportProgress?: boolean): Observable<PermissionGroup>;
    public createPermissionGroup(body?: CreatePermissionGroupRequest, authenticationkey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PermissionGroup>>;
    public createPermissionGroup(body?: CreatePermissionGroupRequest, authenticationkey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PermissionGroup>>;
    public createPermissionGroup(body?: CreatePermissionGroupRequest, authenticationkey?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;
        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post(`${this.basePath}/permissionGroup/createPermissionGroup`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o => FlexiCoreDecycle.retrocycle(o)));
    }

    /**
    * createPermissionGroup
    * creates Permission Group
    * @param body 
    * @param authenticationkey 
    * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
    * @param reportProgress flag to report request and response progress.
    */
    public copyPermissionGroup(body?: PermissionGroupCopy, authenticationkey?: string, observe?: 'body', reportProgress?: boolean): Observable<PermissionGroup>;
    public copyPermissionGroup(body?: PermissionGroupCopy, authenticationkey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PermissionGroup>>;
    public copyPermissionGroup(body?: PermissionGroupCopy, authenticationkey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PermissionGroup>>;
    public copyPermissionGroup(body?: PermissionGroupCopy, authenticationkey?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;
        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post(`${this.basePath}/permissionGroup/copyPermissionGroup`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o => FlexiCoreDecycle.retrocycle(o)));
    }

    /**
   * createPermissionGroup
   * creates Permission Group
   * @param body 
   * @param authenticationkey 
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
    public updatePermissionGroup(body?: UpdatePermissionGroup, authenticationkey?: string, observe?: 'body', reportProgress?: boolean): Observable<PermissionGroup>;
    public updatePermissionGroup(body?: UpdatePermissionGroup, authenticationkey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PermissionGroup>>;
    public updatePermissionGroup(body?: UpdatePermissionGroup, authenticationkey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PermissionGroup>>;
    public updatePermissionGroup(body?: UpdatePermissionGroup, authenticationkey?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;
        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post(`${this.basePath}/permissionGroup/updatePermissionGroup`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o => FlexiCoreDecycle.retrocycle(o)));
    }

    /**
     * listPermissionGroups
     * lists permission groups 
     * @param body 
     * @param authenticationkey 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listPermissionGroups(body?: FilteringInformationHolder, authenticationkey?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<PermissionGroup>>;
    public listPermissionGroups(body?: FilteringInformationHolder, authenticationkey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PermissionGroup>>>;
    public listPermissionGroups(body?: FilteringInformationHolder, authenticationkey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PermissionGroup>>>;
    public listPermissionGroups(body?: FilteringInformationHolder, authenticationkey?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;
        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post(`${this.basePath}/permissionGroup/listPermissionGroups`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o => FlexiCoreDecycle.retrocycle(o)));
    }
}

