/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V1.1.0
 * Contact: avishaybennatan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpEvent } from '@angular/common/http';

import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { TenantToUser } from '../model/tenantToUser';

import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';
import { FlexiCoreDecycle } from './api';

import { TenantToUserCreate, TenantToUserUpdate, TenantToUserFilter, PaginationResponse } from '../model/models';


@Injectable()
export class TenantToUsersService {

    protected basePath = 'https://192.168.14.71:8180/FlexiCore/rest';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }




    /**
    * 
    * 
    * @param authenticationkey The AuthenticationKey retrieved when sign-in into the system
    * @param pagesize Number of entries to be retrieved per page or -1 for full list
    * @param currentpage The current page or -1 for full list
    * @param body 
    * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
    * @param reportProgress flag to report request and response progress.
    */
    public getAllTenantToUsers(authenticationkey?: string, body?: TenantToUserFilter, observe?: 'body', reportProgress?: boolean): Observable<PaginationResponse<TenantToUser>>;
    public getAllTenantToUsers(authenticationkey?: string, body?: TenantToUserFilter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PaginationResponse<TenantToUser>>>;
    public getAllTenantToUsers(authenticationkey?: string, body?: TenantToUserFilter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PaginationResponse<TenantToUser>>>;
    public getAllTenantToUsers(authenticationkey?: string, body?: TenantToUserFilter, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;
        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PaginationResponse<TenantToUser>>(`${this.basePath}/tenantToUser/getAllTenantToUsers`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o => FlexiCoreDecycle.retrocycle(o)));
    }

    /**
    * 
    * 
    * @param authenticationkey The AuthenticationKey retrieved when sign-in into the system
    * @param body 
    * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
    * @param reportProgress flag to report request and response progress.
    */
    public updateTenantToUser(authenticationkey?: string, body?: TenantToUserUpdate, observe?: 'body', reportProgress?: boolean): Observable<TenantToUser>;
    public updateTenantToUser(authenticationkey?: string, body?: TenantToUserUpdate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TenantToUser>>;
    public updateTenantToUser(authenticationkey?: string, body?: TenantToUserUpdate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TenantToUser>>;
    public updateTenantToUser(authenticationkey?: string, body?: TenantToUserUpdate, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;
        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }


        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<TenantToUser>(`${this.basePath}/tenantToUser/updateTenantToUser`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o => FlexiCoreDecycle.retrocycle(o)));
    }


    /**
    * 
    * 
    * @param authenticationkey The AuthenticationKey retrieved when sign-in into the system
    * @param body 
    * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
    * @param reportProgress flag to report request and response progress.
    */
    public createTenantToUser(authenticationkey?: string, body?: TenantToUserCreate, observe?: 'body', reportProgress?: boolean): Observable<TenantToUser>;
    public createTenantToUser(authenticationkey?: string, body?: TenantToUserCreate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TenantToUser>>;
    public createTenantToUser(authenticationkey?: string, body?: TenantToUserCreate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TenantToUser>>;
    public createTenantToUser(authenticationkey?: string, body?: TenantToUserCreate, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;
        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }


        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<TenantToUser>(`${this.basePath}/tenantToUser/createTenantToUser`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o => FlexiCoreDecycle.retrocycle(o)));
    }


}
