/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V1.1.0
 * Contact: avishaybennatan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { FlexiCoreDecycle } from './flexiCoreDecycle';
import { Observable } from 'rxjs';

import { map } from 'rxjs/operators';

import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';
import { HttpHeaders, HttpClient, HttpResponse, HttpEvent } from '@angular/common/http';
import { PaginationResponse } from '../model/models';
import { TotpSecurityPolicyCreate } from '../model/totpSecurityPolicyCreate';
import { TotpSecurityPolicy } from '../model/totpSecurityPolicy';
import { TotpSecurityPolicyUpdate } from '../model/totpSecurityPolicyUpdate';
import { TotpSecurityPolicyFilter } from '../model/totpSecurityPolicyFilter';


@Injectable()
export class TotpSecurityPolicyService {

    protected basePath = 'https://192.168.0.41:8080/FlexiCore/rest';
    public defaultHeaders = new HttpHeaders();
    public configuration: Configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            let url = basePath.split("/");
            this.basePath = url[0] + "//" + url[2];
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     *  
     * @param authenticationkey The AuthenticationKey retrieved when sign-in into the system
     * @param body 
     */
    public createPolicy(authenticationkey?: string, body?: TotpSecurityPolicyCreate, observe?: 'body', reportProgress?: boolean): Observable<TotpSecurityPolicy>;
    public createPolicy(authenticationkey?: string, body?: TotpSecurityPolicyCreate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TotpSecurityPolicy>>;
    public createPolicy(authenticationkey?: string, body?: TotpSecurityPolicyCreate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TotpSecurityPolicy>>;
    public createPolicy(authenticationkey?: string, body?: TotpSecurityPolicyCreate, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<TotpSecurityPolicy>(`${this.basePath}/totpSecurityPolicy/create`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o=>FlexiCoreDecycle.retrocycle(o)));
    }

    /**
     *  
     * @param authenticationkey The AuthenticationKey retrieved when sign-in into the system
     * @param body 
     */
    public updatePolicy(authenticationkey?: string, body?: TotpSecurityPolicyUpdate, observe?: 'body', reportProgress?: boolean): Observable<TotpSecurityPolicy>;
    public updatePolicy(authenticationkey?: string, body?: TotpSecurityPolicyUpdate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TotpSecurityPolicy>>;
    public updatePolicy(authenticationkey?: string, body?: TotpSecurityPolicyUpdate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TotpSecurityPolicy>>;
    public updatePolicy(authenticationkey?: string, body?: TotpSecurityPolicyUpdate, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<TotpSecurityPolicy>(`${this.basePath}/totpSecurityPolicy/update`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o=>FlexiCoreDecycle.retrocycle(o)));
    }

    /**
     *  
     * @param authenticationkey The AuthenticationKey retrieved when sign-in into the system
     * @param body 
     */
    public getAllPolicy(authenticationkey?: string, body?: TotpSecurityPolicyFilter, observe?: 'body', reportProgress?: boolean): Observable<PaginationResponse<TotpSecurityPolicy>>;
    public getAllPolicy(authenticationkey?: string, body?: TotpSecurityPolicyFilter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PaginationResponse<TotpSecurityPolicy>>>;
    public getAllPolicy(authenticationkey?: string, body?: TotpSecurityPolicyFilter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PaginationResponse<TotpSecurityPolicy>>>;
    public getAllPolicy(authenticationkey?: string, body?: TotpSecurityPolicyFilter, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        if (authenticationkey !== undefined && authenticationkey !== null) {
            headers = headers.set('authenticationkey', String(authenticationkey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PaginationResponse<TotpSecurityPolicy>>(`${this.basePath}/totpSecurityPolicy/getAll`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        ).pipe(map(o=>FlexiCoreDecycle.retrocycle(o)));
    }
}
